// Canonical dog-breed list for the global breed autocomplete (BreedSelect).
// Sourced from AKC/FCI/UKC recognised breeds plus common cross-breeds and a
// catch-all. Free-text entry is still allowed in the UI, so this list does not
// need to be exhaustive — it just covers the breeds a trainer will reach for.
//
// Keep this a plain, alphabetically-sorted string array. "Mixed breed / Other"
// is intentionally last so it reads as the fallback option.

export const DOG_BREEDS: string[] = [
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akita',
  'Alaskan Klee Kai',
  'Alaskan Malamute',
  'American Bulldog',
  'American Cocker Spaniel',
  'American English Coonhound',
  'American Eskimo Dog',
  'American Foxhound',
  'American Hairless Terrier',
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Anatolian Shepherd Dog',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Shepherd',
  'Australian Terrier',
  'Azawakh',
  'Barbet',
  'Basenji',
  'Basset Fauve de Bretagne',
  'Basset Hound',
  'Beagle',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Bergamasco Sheepdog',
  'Berger Picard',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Black and Tan Coonhound',
  'Black Russian Terrier',
  'Bloodhound',
  'Bluetick Coonhound',
  'Boerboel',
  'Bolognese',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Boykin Spaniel',
  'Bracco Italiano',
  'Briard',
  'Brittany',
  'Brussels Griffon',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Cairn Terrier',
  'Canaan Dog',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Catahoula Leopard Dog',
  'Cavalier King Charles Spaniel',
  'Cavoodle',
  'Cesky Terrier',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chinese Crested',
  'Chinese Shar-Pei',
  'Chinook',
  'Chow Chow',
  'Clumber Spaniel',
  'Cockapoo',
  'Cocker Spaniel',
  'Collie',
  'Coton de Tulear',
  'Curly-Coated Retriever',
  'Dachshund',
  'Dalmatian',
  'Dandie Dinmont Terrier',
  'Doberman Pinscher',
  'Dogo Argentino',
  'Dogue de Bordeaux',
  'Dutch Shepherd',
  'English Cocker Spaniel',
  'English Foxhound',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Spaniel',
  'Entlebucher Mountain Dog',
  'Estrela Mountain Dog',
  'Eurasier',
  'Field Spaniel',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'Fox Terrier (Smooth)',
  'Fox Terrier (Wire)',
  'French Bulldog',
  'German Pinscher',
  'German Shepherd Dog',
  'German Shorthaired Pointer',
  'German Wirehaired Pointer',
  'Giant Schnauzer',
  'Glen of Imaal Terrier',
  'Golden Retriever',
  'Goldendoodle',
  'Gordon Setter',
  'Great Dane',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greyhound',
  'Groodle',
  'Harrier',
  'Havanese',
  'Huntaway',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Jack Russell Terrier',
  'Japanese Chin',
  'Japanese Spitz',
  'Keeshond',
  'Kerry Blue Terrier',
  'King Charles Spaniel',
  'Komondor',
  'Kooikerhondje',
  'Kuvasz',
  'Labradoodle',
  'Labrador Retriever',
  'Lagotto Romagnolo',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Leonberger',
  'Lhasa Apso',
  'Lowchen',
  'Maltese',
  'Maltipoo',
  'Manchester Terrier',
  'Maremma Sheepdog',
  'Mastiff',
  'Miniature American Shepherd',
  'Miniature Bull Terrier',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Mudi',
  'Neapolitan Mastiff',
  'Newfoundland',
  'Norfolk Terrier',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Papillon',
  'Parson Russell Terrier',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Plott Hound',
  'Pointer',
  'Polish Lowland Sheepdog',
  'Pomeranian',
  'Poodle (Miniature)',
  'Poodle (Standard)',
  'Poodle (Toy)',
  'Portuguese Podengo',
  'Portuguese Water Dog',
  'Pug',
  'Puli',
  'Pumi',
  'Pyrenean Shepherd',
  'Rat Terrier',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Russell Terrier',
  'Saint Bernard',
  'Saluki',
  'Samoyed',
  'Schipperke',
  'Schnoodle',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Siberian Husky',
  'Silken Windhound',
  'Silky Terrier',
  'Skye Terrier',
  'Sloughi',
  'Soft Coated Wheaten Terrier',
  'Spanish Water Dog',
  'Spinone Italiano',
  'Spoodle',
  'Staffordshire Bull Terrier',
  'Standard Schnauzer',
  'Sussex Spaniel',
  'Swedish Vallhund',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Toy Fox Terrier',
  'Treeing Walker Coonhound',
  'Vizsla',
  'Weimaraner',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Wire Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla',
  'Working Cocker Spaniel',
  'Xoloitzcuintli',
  'Yorkshire Terrier',
  'Mixed breed / Other',
]
