'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Alert } from '@/components/ui/alert'
import { Sparkles, ChevronDown, ChevronUp } from 'lucide-react'

interface Client {
  id: string
  user: { name: string | null; email: string | null }
  dog: { name: string } | null
}

interface GeneratedTask {
  dayOffset: number
  title: string
  description?: string
  repetitions?: number
}

export function AIPlanGenerator({ clients }: { clients: Client[] }) {
  const router = useRouter()
  const [clientId, setClientId] = useState('')
  const [goal, setGoal] = useState('')
  const [durationWeeks, setDurationWeeks] = useState(4)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [tasks, setTasks] = useState<GeneratedTask[] | null>(null)
  const [saving, setSaving] = useState(false)
  const [expanded, setExpanded] = useState<number | null>(null)

  async function generate(e: React.FormEvent) {
    e.preventDefault()
    setError(null)
    setTasks(null)
    setLoading(true)
    try {
      const res = await fetch('/api/ai/generate-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ clientId, goal, durationWeeks }),
      })
      const data = await res.json()
      if (!res.ok) { setError(data.error ?? 'Failed to generate plan.'); return }
      setTasks(data.tasks)
    } finally {
      setLoading(false)
    }
  }

  async function saveAsTemplate() {
    if (!tasks) return
    setSaving(true)
    setError(null)
    try {
      const res = await fetch('/api/templates', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: `AI Plan — ${goal.slice(0, 40)}`,
          description: `Generated by AI. Goal: ${goal}`,
          tasks: tasks.map((t, i) => ({ ...t, order: i })),
        }),
      })
      const data = await res.json()
      if (!res.ok) { setError('Failed to save template.'); return }
      router.push(`/templates/${data.id}`)
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="flex flex-col gap-5">
      <form onSubmit={generate} className="flex flex-col gap-4">
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-slate-700">Client</label>
          <select
            value={clientId}
            onChange={e => setClientId(e.target.value)}
            required
            className="h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="">Select a client…</option>
            {clients.map(c => (
              <option key={c.id} value={c.id}>
                {c.user.name ?? c.user.email}{c.dog ? ` · ${c.dog.name}` : ''}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-slate-700">Training goal</label>
          <textarea
            value={goal}
            onChange={e => setGoal(e.target.value)}
            required
            minLength={10}
            maxLength={500}
            rows={3}
            placeholder="e.g. Teach loose-lead walking and basic recall for a reactive 2-year-old Labrador"
            className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
          />
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-slate-700">Duration</label>
          <select
            value={durationWeeks}
            onChange={e => setDurationWeeks(Number(e.target.value))}
            className="h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            {[1, 2, 3, 4, 6, 8, 12].map(w => (
              <option key={w} value={w}>{w} week{w !== 1 ? 's' : ''}</option>
            ))}
          </select>
        </div>

        {error && <Alert variant="error">{error}</Alert>}

        <Button type="submit" loading={loading} className="w-full">
          <Sparkles className="h-4 w-4" />
          {loading ? 'Generating…' : 'Generate training plan'}
        </Button>
      </form>

      {tasks && (
        <div className="flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <p className="font-semibold text-slate-900">{tasks.length} tasks generated</p>
            <Button size="sm" variant="secondary" onClick={saveAsTemplate} loading={saving}>
              Save as template
            </Button>
          </div>
          <div className="flex flex-col gap-2">
            {tasks.map((task, i) => (
              <div key={i} className="rounded-xl border border-slate-200 bg-white">
                <button
                  type="button"
                  onClick={() => setExpanded(expanded === i ? null : i)}
                  className="w-full flex items-center gap-3 px-4 py-3 text-left"
                >
                  <span className="flex-shrink-0 h-7 w-7 rounded-full bg-blue-100 text-blue-700 text-xs font-bold flex items-center justify-center">
                    {task.dayOffset}
                  </span>
                  <p className="flex-1 text-sm font-medium text-slate-900">{task.title}</p>
                  {task.repetitions && <span className="text-xs text-slate-500">{task.repetitions} reps</span>}
                  {expanded === i ? <ChevronUp className="h-4 w-4 text-slate-400" /> : <ChevronDown className="h-4 w-4 text-slate-400" />}
                </button>
                {expanded === i && task.description && (
                  <div className="px-4 pb-3">
                    <p className="text-sm text-slate-600">{task.description}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
