-- No-op (intentionally).
--
-- This migration originally re-scheduled the pm-streak-update pg_cron
-- job. That's been moved OUT of migrations entirely: the job command
-- must carry the bearer secret inlined (the GUC approach is privilege-
-- blocked on Supabase — `ALTER DATABASE ... SET` → 42501), and a secret
-- must never be committed to git. So all pm-* cron scheduling is owned
-- by scripts/setup-supabase-crons.ts (reads CRON_SECRET from env at
-- runtime, writes it only into the cron.job table — same trade-off the
-- pre-existing pupmanager-* jobs already accept). Run that script after
-- changing any schedule/endpoint; verify with scripts/check-crons.ts.
--
-- Kept as a recorded migration (rather than deleted) so the migration
-- history stays linear and any environment that already applied an
-- earlier form converges cleanly.
SELECT 1;
