// Help-center content for the shop: products, categories, options, stock, and
// the money side (in-person sales, Stripe payouts, Xero).
//
// Same rules as content.ts — short lines, one action per step, plain English,
// controls named exactly as they appear on screen. Prices are never written
// with a currency symbol: PupManager runs in six currencies.

import type { HelpArticle } from './content'

export const SHOP_ARTICLES: HelpArticle[] = [
  // ── Setting the shop up ───────────────────────────────────────────────────
  {
    slug: 'turn-on-shop',
    title: 'Turn on your client shop',
    category: 'Programmes & products',
    keywords: ['shop', 'store', 'products', 'add-on', 'addon', 'sell', 'enable', 'switch on', 'merch', 'locked'],
    summary: 'The shop is an add-on — switch it on to sell treats, gear and downloads.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Add-ons" tab.',
      'Click the "Client shop" card, then "Learn more →".',
      'Click "Turn on Client shop".',
      '"Products" now opens in the left menu. Until then it shows an "Add-on" tag and takes you here.',
      'Instant sale — selling to someone standing in front of you — comes with it. There is no separate switch.',
    ],
  },
  {
    slug: 'add-first-product',
    title: 'Add something to your shop',
    category: 'Programmes & products',
    keywords: ['product', 'add product', 'new product', 'treats', 'gear', 'lead', 'toy', 'sell'],
    summary: 'List an item clients can buy, with a photo, a price and a shelf.',
    steps: [
      'Click "Products" on the left.',
      'Click "Add product".',
      'Type a "Name", write a "Description", and click "Upload photo".',
      'Type the "Normal price". Leave it blank and clients see "Contact trainer" instead.',
      'Pick a "Category" — that is the shelf it sits on in your shop.',
      'Click "Create product".',
    ],
  },
  {
    slug: 'shop-categories',
    title: 'Sort your shop into categories',
    category: 'Programmes & products',
    keywords: ['category', 'categories', 'shelf', 'shelves', 'group', 'sort', 'sections', 'organise', 'tidy'],
    summary: 'Make shelves like "Treats" and "Leads", then put your products on them.',
    steps: [
      'Click "Products" on the left. The shelves sit in the "Categories" list on the left of the screen.',
      'On a phone, tap the "Categories" bar at the top first.',
      'Click "New category", type a name — "Treats", say — and click "Add".',
      'On a computer, drag a product onto a category to put it on that shelf.',
      'Drag it onto "Uncategorised" to take it off every shelf.',
      'No mouse? Open the product instead and pick the shelf in its "Category" box.',
    ],
  },
  {
    slug: 'reorder-shop',
    title: 'Change the order things appear in your shop',
    category: 'Programmes & products',
    keywords: ['order', 'reorder', 'drag', 'sort', 'first', 'top', 'rearrange', 'shelves'],
    summary: 'Drag products and categories into the order you want clients to see.',
    steps: [
      'Click "Products" on the left.',
      'Drag a product up or down to move it within the shelf you are looking at.',
      'Drag a category up or down to reorder the shelves themselves.',
      'The order you set here is the order your clients see in the shop.',
      'Dragging is a computer thing — on a phone the list stays as you last set it.',
    ],
  },

  // ── Options (variants) ────────────────────────────────────────────────────
  {
    slug: 'product-options',
    title: 'Sell one product in different sizes',
    category: 'Programmes & products',
    keywords: ['options', 'variants', 'sizes', 'small', 'medium', 'large', 'colours', 'colors', 'harness', 'choices', 'sku'],
    summary: 'Small, Medium, Large — one product, with a choice the client makes before buying.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Click the "Options" tab.',
      'Type a name in the "Add an option" box — "Small", "Red", "1kg" — and press the plus.',
      'Add the rest the same way. Drag the rows to change the order clients see.',
      'Click "Save options".',
      'Once a product has options, a client has to pick one before they can buy.',
    ],
  },
  {
    slug: 'option-prices',
    title: 'Price each size differently',
    category: 'Programmes & products',
    keywords: ['options', 'variants', 'price', 'sizes', 'different price', 'cost more', 'blank', 'sale'],
    summary: 'Leave a size blank to charge the product price, or give it one of its own.',
    steps: [
      'Click "Products" on the left, open the product, then click the "Options" tab.',
      'Leave a size\'s price box blank and it charges the product\'s own price. The grey number shows you what that is.',
      'Type a price on a size to charge that instead — a Large that costs more, say.',
      'The figure on the right of the row is what a client will actually pay.',
      'Click "Save options".',
      'A size with its own price is left out of any sale price you set on the product.',
    ],
  },
  {
    slug: 'option-stock',
    title: 'Count each size separately',
    category: 'Programmes & products',
    keywords: ['options', 'variants', 'stock', 'sizes', 'count', 'per size', 'on hand', 'sold out'],
    summary: 'A harness in three sizes is three shelves — each size is counted on its own.',
    steps: [
      'Click "Products" on the left, open the product, then click the "Options" tab.',
      'On a size you have just added, type an opening count in its "Stock" box, then click "Save options".',
      'On a size already saved, click the button on its row — it reads "Not counted" or "3 on hand".',
      'Pick what happened, type how many, and click "Record it".',
      'The product\'s own "Units on hand" is not used once it has options — each size is counted by itself.',
      'A product is only sold out once every visible size is.',
    ],
  },
  {
    slug: 'option-photo-notes',
    title: 'Give a size its own photo and notes',
    category: 'Programmes & products',
    keywords: ['options', 'variants', 'photo', 'picture', 'image', 'notes', 'description', 'per size', 'colour'],
    summary: 'Show a different picture or a different blurb for one size or colour.',
    steps: [
      'Click "Products" on the left, open the product, then click the "Options" tab.',
      'Click the small picture at the start of that option\'s row.',
      'Click "Upload photo" to give that one its own picture.',
      'Type in "Notes for this option" — "fits 12–18kg", say.',
      'Click "Done", then "Save options".',
      'Leave either blank and the product\'s own photo and description are used. A dot on the picture means that size has something of its own.',
    ],
  },
  {
    slug: 'hide-an-option',
    title: 'Take one size off sale',
    category: 'Programmes & products',
    keywords: ['options', 'variants', 'hide', 'visible', 'discontinued', 'stop selling', 'remove size', 'sold out'],
    summary: 'Stop offering one size without deleting it or touching the others.',
    steps: [
      'Click "Products" on the left, open the product, then click the "Options" tab.',
      'Untick "Visible" on that row.',
      'Click "Save options". Clients no longer see it, and it can\'t hold a sold-out product open.',
      'Tick it again any time to bring it back, with its count intact.',
      'Use the × at the end of the row only if you want it gone for good.',
    ],
  },

  // ── Stock ─────────────────────────────────────────────────────────────────
  {
    slug: 'start-counting-stock',
    title: 'Start counting a product\'s stock',
    category: 'Programmes & products',
    keywords: ['stock', 'inventory', 'count', 'units on hand', 'how many', 'stocktake', 'track', 'not counted'],
    summary: 'Tell PupManager how many you have, and it counts them down as they go out.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Find "Units on hand" under the description.',
      'Click "Start counting".',
      'Type the number you have in "How many are there now".',
      'Click "Set the count". At zero it stops being sellable until you add more.',
      'Leave it as "Not counted" for anything you never run out of — a download, or a made-to-order item.',
    ],
  },
  {
    slug: 'add-stock',
    title: 'Book in a delivery',
    category: 'Programmes & products',
    keywords: ['stock', 'add stock', 'delivery', 'restock', 'arrived', 'received', 'top up', 'wholesaler', 'inventory'],
    summary: 'Put units back on the shelf when an order turns up.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Under "Units on hand", click "Add stock".',
      'Leave "What happened" on "Stock arrived".',
      'Type how many arrived in "How many".',
      'Add a note if you like — "Delivery from the wholesaler".',
      'Click "Record it". The count goes up and the delivery is saved to the history.',
    ],
  },
  {
    slug: 'correct-stock-count',
    title: 'Correct a count after a stocktake',
    category: 'Programmes & products',
    keywords: ['stocktake', 'stock take', 'correct', 'wrong', 'recount', 'adjust', 'damaged', 'lost', 'broken', 'missing'],
    summary: 'Set the number to what you actually counted, or write off what went missing.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Under "Units on hand", click "Add stock".',
      'Change "What happened" to "I counted them".',
      'Type the number you counted in "How many are there now", then click "Set the count".',
      'Know what went? Choose "Damaged" or "Lost" instead and type how many — that reads better a month later than a bare correction.',
      'Either way the difference is recorded, so nothing changes without a reason attached to it.',
    ],
  },
  {
    slug: 'stock-history',
    title: 'See where your stock went',
    category: 'Programmes & products',
    keywords: ['stock', 'history', 'movements', 'audit', 'ledger', 'who bought', 'went missing', 'shrinkage', 'explain'],
    summary: 'Every movement is recorded, so the number on the shelf can always be explained.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Under "Units on hand", click "Add stock" (or "Start counting").',
      'Scroll to "Recent movements".',
      'Each line says what happened, when, who it was for, the change, and how many were left after it.',
      'Sales, deliveries, write-offs and corrections all land here — nothing changes the count without a line.',
      'For a product with sizes, open the "Options" tab and click that size\'s stock button instead. Each size keeps its own history.',
    ],
  },

  // ── Listing details ───────────────────────────────────────────────────────
  {
    slug: 'digital-download',
    title: 'Sell a digital download',
    category: 'Programmes & products',
    keywords: ['digital', 'download', 'pdf', 'ebook', 'guide', 'file', 'video', 'upload', 'no stock'],
    summary: 'Sell a file — a guide, a plan, a printable — that clients get in the app.',
    steps: [
      'Click "Products" on the left and open the product (or click "Add product").',
      'Scroll to "Type" and click "Digital download".',
      'Click "Upload file" and pick the file. Or paste a link in "…or paste a URL".',
      'Leave "Units on hand" blank — a download can\'t run out.',
      'Click "Save changes".',
      'Once a client has paid, "Download" appears on the item in their shop, and it also sits under "Your library" on their home screen. No email carries the file.',
    ],
  },
  {
    slug: 'product-on-sale',
    title: 'Put a product on sale',
    category: 'Programmes & products',
    keywords: ['sale', 'discount', 'reduced', 'markdown', 'special', 'offer', 'sale price', 'struck through'],
    summary: 'Set a lower price and clients see the old one struck through.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Find the "Price" box.',
      'Check the everyday price is in "Normal price".',
      'Type the lower price in "Sale price". The line underneath tells you the saving.',
      'Click "Save changes".',
      'Click "Clear" beside the sale price to end the sale.',
    ],
  },
  {
    slug: 'feature-or-hide-product',
    title: 'Feature a product, or hide it',
    category: 'Programmes & products',
    keywords: ['feature', 'featured', 'hide', 'hidden', 'visible', 'unpublish', 'take off sale', 'home screen', 'promote'],
    summary: 'Push something to your clients\' home screen, or take it off the shop for now.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Scroll to "Selling".',
      'Tick "Feature on client home" to put it on your clients\' home screen.',
      'Untick "Visible to clients" to take it off the shop without deleting it.',
      'Click "Save changes".',
      'To copy or delete it, use the "⋯" button beside Save.',
    ],
  },
  {
    slug: 'preview-shop',
    title: 'See your shop the way a client does',
    category: 'Programmes & products',
    keywords: ['preview', 'view as client', 'what they see', 'check', 'test', 'shop', 'looks like'],
    summary: 'Open your shop in a new tab, exactly as your clients see it.',
    steps: [
      'Click "Products" on the left and open a product.',
      'Click "Preview" at the top.',
      'Your shop opens in a new tab, as one of your clients sees it.',
      'It shows what is saved — click "Save changes" first if you have just edited something.',
      'Close the tab when you are done. Your editing screen is untouched behind it.',
    ],
  },
  {
    slug: 'product-list-columns',
    title: 'Choose what the product list shows',
    category: 'Programmes & products',
    keywords: ['columns', 'list view', 'table', 'grid', 'stock column', 'show', 'view', 'layout'],
    summary: 'Show or hide the Category, Type, Stock and Status columns.',
    steps: [
      'Click "Products" on the left.',
      'At the top right, click the "List view" button.',
      'Click the columns button beside it — hover and it reads "Choose columns".',
      'Tick "Category", "Type", "Stock" or "Status" to show them.',
      'Your choice is remembered on this computer. (Columns are a computer thing — a phone keeps the simple list.)',
    ],
  },

  // ── Buying, from the client's side ────────────────────────────────────────
  {
    slug: 'client-basket',
    title: 'How a client buys several things at once',
    category: 'Programmes & products',
    keywords: ['basket', 'cart', 'checkout', 'multiple', 'one payment', 'together', 'sold out', 'shopping'],
    summary: 'A client can put products and classes in one basket and pay for the lot once.',
    steps: [
      'Your client opens your shop and taps "Add to basket" on each thing they want.',
      'They can add classes from their booking screen to the same basket.',
      'A "View basket" bar appears at the bottom of their screen with the running total.',
      'They tap it, check the list, change quantities, then tap "Pay" — one card payment for everything.',
      'If something sold out while they were shopping, the whole basket is refused and the row that failed is named, so they know which one it was.',
      'They tap "Remove it and carry on", and pay for the rest.',
    ],
  },
  {
    slug: 'client-buys-one-thing',
    title: 'What a client sees when they buy one item',
    category: 'Programmes & products',
    keywords: ['buy', 'client', 'shop', 'checkout', 'stripe', 'out of stock', 'only 2 left', 'choose an option'],
    summary: 'The straight-through buy, and the messages a client can hit on the way.',
    steps: [
      'Your client opens the item in your shop and taps "Buy".',
      'A product with sizes shows "Choose one" first — they pick a size, then the button becomes "Buy".',
      'They pay by card on Stripe\'s page and get a receipt by email.',
      'They only see a stock number if you are counting that item — "Only 2 left", or "Out of stock — ask when it\'s back."',
      'If it is not payable, the button reads "Add to next session" instead, and you settle it later.',
    ],
  },

  // ── Getting paid ──────────────────────────────────────────────────────────
  {
    slug: 'instant-sale',
    title: 'Sell to a client standing in front of you',
    category: 'Getting paid',
    keywords: ['instant sale', 'pos', 'till', 'counter', 'in person', 'face to face', 'new sale', 'qr', 'sell now'],
    summary: 'Ring up a sale on the spot, and take the money now or later.',
    steps: [
      'Click the "+" button — top right on a computer, the circle at the bottom right on a phone.',
      'Choose "New sale", then pick the client. Not on the list? Use "New client" to add them as you sell.',
      'Tap what they are buying. A product with sizes opens "Which one?" so you pick the size.',
      'Nothing in your list matches? Click "Something else" and type a description and an amount.',
      'Click "Continue to payment".',
      'Click "Take payment now" to show a QR they scan on their phone, or "Record as unpaid" to file it in Finances and settle later.',
    ],
  },
  {
    slug: 'instant-sale-stock',
    title: 'What an over-the-counter sale does to your stock',
    category: 'Getting paid',
    keywords: ['instant sale', 'pos', 'stock', 'counter', 'sold out', 'refused', 'purchases', 'who bought', 'till'],
    summary: 'A sale at the counter takes the item off the shelf, just like an online one.',
    steps: [
      'Every catalogue item you tap in a sale comes off your stock the moment the sale is saved.',
      'It also shows on that product\'s "Purchases" tab, so "who bought this" stays right.',
      'A product with none left can\'t be tapped — its tile is greyed and reads "Out of stock".',
      'If the last one goes while you are ringing up, the sale is refused and you are told exactly how many are left.',
      'A "Something else" line is just words and an amount — it does not touch stock.',
      'Sold one back to you? Open the product, click "Add stock", and choose "Came back to me".',
    ],
  },
  {
    slug: 'sell-to-a-guest',
    title: 'Sell to someone who isn\'t a client',
    category: 'Getting paid',
    keywords: ['guest', 'walk up', 'stranger', 'not a client', 'one off', 'card only', 'instant sale', 'market stall'],
    summary: 'Take a card payment from a passer-by without making them a client.',
    steps: [
      'Click the "+" button and choose "New sale".',
      'On "Who\'s it for?", click "Guest".',
      'Tap what they are buying, then click "Continue to payment".',
      'A guest sale is card only — show them the QR and they pay on their own phone.',
      'There is no "Record as unpaid" for a guest: there is no account to chase later.',
      'A guest sale does not move your stock, so adjust the count yourself afterwards if you are counting that item.',
    ],
  },
  {
    slug: 'take-payment-for-session',
    title: 'Take payment for a session',
    category: 'Getting paid',
    keywords: ['session', 'payment', 'unpaid', 'settle', 'qr', 'collect', 'owed', 'pay now', 'after the session'],
    summary: 'Settle what a client already owes on a session, and add anything they buy on the day.',
    steps: [
      'Click "Schedule" on the left and open the session.',
      'Click "Payment" in the row of actions. (It only shows when something is owed.)',
      'What they already owe is listed for you.',
      'Tap anything extra they are buying — it goes on the same invoice, not a second one.',
      'Click "Continue to payment", then "Take payment now" to show a QR.',
      'They scan it and pay by card. A payment request also goes to their phone.',
    ],
  },
  {
    slug: 'how-money-reaches-you',
    title: 'How the money gets from your client to you',
    category: 'Getting paid',
    keywords: ['payouts', 'stripe', 'connect', 'bank', 'fees', 'when do i get paid', 'money', 'card fee', 'surcharge'],
    summary: 'Clients pay into your own Stripe account, and Stripe pays it out to your bank.',
    steps: [
      'Set payments up first: Settings → "Integrations" → "Card payments" → "Set up payments".',
      'From then on, a client paying by card pays into your own Stripe account. The payment is yours — your name is on their statement.',
      'Stripe pays it out to the bank account you gave them, on their usual payout schedule.',
      'Stripe\'s card fee comes off your side. Turn on "Pass card fees to clients" if you would rather they covered it.',
      'Click "Open Stripe dashboard" on that screen to see your payouts.',
      'Turn "Accept payments" off any time to make prices display-only.',
    ],
  },
  {
    slug: 'connect-xero',
    title: 'Connect Xero',
    category: 'Getting paid',
    keywords: ['xero', 'accounting', 'books', 'sync', 'bookkeeper', 'accountant', 'connect', 'integration'],
    summary: 'Link your Xero organisation so invoices and payments stop being typed twice.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Configure" tab and turn "Xero" on. It is free, and sits under "Connected to other apps".',
      'Click "Connect Xero" on that row.',
      'Sign in to Xero and choose the organisation to link.',
      'You land back on a card reading "Connected ·" and your organisation name.',
      'To unlink later, click "Disconnect" on the same card. New invoices and payments stop syncing.',
    ],
  },
  {
    slug: 'xero-setup',
    title: 'Tell Xero where the money goes',
    category: 'Getting paid',
    keywords: ['xero', 'accounts', 'chart of accounts', 'mapping', 'clearing account', 'bank', 'tax rate', 'reconcile'],
    summary: 'A few one-time choices so everything posts to the right place in Xero.',
    steps: [
      'Open Settings, click the "Integrations" tab, then open the "Xero" card.',
      'Under "Finish your Xero setup", pick "Your real bank account" — the one Stripe pays into.',
      'Pick "Your Stripe clearing account". Don\'t have one? Read "Why you need one", add it in Xero, then come back.',
      'Pick "Where card fees are recorded" and "Your default tax rate".',
      'Under "Accounts you use", add each income account you sell against, name it, and mark one "Default".',
      'Click "Save setup". Invoices and payments then sync across on their own.',
    ],
  },
  {
    slug: 'product-xero-account',
    title: 'Send a product\'s money to the right Xero account',
    category: 'Getting paid',
    keywords: ['xero', 'account code', 'income account', 'product', 'coding', 'revenue', 'mapping', 'per product'],
    summary: 'Code one product to its own income account instead of your default.',
    steps: [
      'Click "Products" on the left and open the product.',
      'Find "Xero income account" in the "Price" box.',
      'Pick the account this product\'s money should be recorded against.',
      'Leave it on "Use my default income account" to use the one you marked "Default" in your Xero setup.',
      'Click "Save changes".',
      'This box only appears once Xero is connected and you have added some accounts.',
    ],
  },
]
