// Help-center content: the trainer's own TOOLS, and the things PupManager
// plugs into.
//
// The Library, the Route planner, Google Calendar, Locations and the app-wide
// settings had no guides at all. Tags had one ("use-tags" in content.ts) that
// only covers putting a tag on something — the rest of the tag screens are
// covered here.
//
// Same voice as content.ts: short lines, one action per step, plain English,
// controls named exactly as they appear on screen. The left menu is renameable
// (Settings → What you call things), so anywhere a step names a menu item a
// trainer may have changed, it says so.

import type { HelpArticle } from './content'

export const TOOL_ARTICLES: HelpArticle[] = [
  // ── The Library ───────────────────────────────────────────────────────────
  {
    slug: 'library-overview',
    title: 'How your Library is organised',
    category: 'Sessions & notes',
    keywords: ['library', 'resources', 'exercises', 'tasks', 'categories', 'themes', 'items', 'structure', 'what is the library'],
    summary: 'Categories hold themes, themes hold items. An item is one exercise you hand out.',
    steps: [
      'Click "Library" on the left, under "Tools". (You may have renamed it.)',
      'The top level is your categories — "Obedience", "Puppy", whatever suits you.',
      'Open a category and you see its themes — "Basic commands", "Leash manners".',
      'Open a theme and you see its items. An item is one exercise: instructions, a picture, a handout.',
      'On a computer the whole tree also sits in a column on the left, so you can jump anywhere.',
    ],
  },
  {
    slug: 'library-turn-on',
    title: 'Turn the Library on or off',
    category: 'Sessions & notes',
    keywords: ['library', 'missing', 'no library', 'switch on', 'training library', 'configure', 'gone'],
    summary: 'The Library is included and on out of the box. Its switch lives on Settings → Configure.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Configure" tab.',
      'Find "Training library" under "Running the business".',
      'Turn the switch on. It costs nothing — everything on Configure is included.',
      'The "Library" row comes back in your left menu.',
    ],
  },
  {
    slug: 'add-library-category',
    title: 'Make a library category',
    category: 'Sessions & notes',
    keywords: ['library', 'category', 'new category', 'folder', 'top level', 'add'],
    summary: 'Categories are the top level of your Library.',
    steps: [
      'Click "Library" on the left. (You may have renamed it.)',
      'On a computer, look at the "Library" column on the left of the screen.',
      'Click "New category" under the list in that column.',
      'Type a name — "Obedience", say — and click "Add".',
      'It opens straight away, ready for you to add themes.',
    ],
  },
  {
    slug: 'add-library-theme',
    title: 'Add a theme inside a category',
    category: 'Sessions & notes',
    keywords: ['library', 'theme', 'new theme', 'sub folder', 'group', 'inside a category'],
    summary: 'Themes group the items inside one category.',
    steps: [
      'Click "Library" on the left, then open a category.',
      'Click "New theme" beside the "Themes" heading.',
      'Type a name — "Basic commands", say.',
      'Click "Add". The theme opens, ready for items.',
    ],
  },
  {
    slug: 'add-library-item',
    title: 'Add an item to your library',
    category: 'Sessions & notes',
    keywords: ['library', 'item', 'exercise', 'task', 'new item', 'instructions', 'reps', 'repetitions'],
    summary: 'One item is one exercise — its instructions and how many reps.',
    steps: [
      'Click "Library" on the left, then open a category, then a theme.',
      'Click "New item" beside the "Items" heading.',
      'Type a name — "Loose-lead walking", say — and click "Add". The item opens.',
      'Write what to do in "Instructions". You can use headings, bold and lists.',
      'Put a number in "Repetitions" if there is one, then click "Save".',
    ],
  },
  {
    slug: 'library-item-media',
    title: 'Add pictures, videos and handouts to an item',
    category: 'Sessions & notes',
    keywords: ['library', 'media', 'photo', 'picture', 'video', 'clip', 'handout', 'worksheet', 'pdf', 'attachment', 'link', 'upload'],
    summary: 'Everything you attach to an item is one list you drag into order.',
    steps: [
      'Open the item in your Library.',
      'Scroll to "Media" and click "Add media".',
      'Choose what you are attaching: "A picture", "A video", "A handout" or "A link".',
      'For a picture or a handout, pick the file. A handout has to be a PDF, up to 20 MB.',
      'For a video, paste a YouTube or Vimeo link and click "Add it" — or use "or upload a clip" for one you filmed.',
      'Give it a name if you like, then click "Save" at the top of the item.',
    ],
  },
  {
    slug: 'library-media-order',
    title: 'Choose the picture and handout a client sees',
    category: 'Sessions & notes',
    keywords: ['library', 'media', 'order', 'reorder', 'drag', 'cover', 'thumbnail', 'first', 'main photo', 'which handout'],
    summary: 'The order you drag things into is the order clients meet them — and it picks the cover.',
    steps: [
      'Open the item in your Library and find the "Media" list.',
      'Drag a row by its handle to move it up or down.',
      'The first picture in the list becomes the item\'s cover image.',
      'The first PDF in the list becomes the item\'s handout.',
      'Click the name box on a row to rename it, or the X to remove it.',
      'Click "Save" at the top. Up to 20 things can hang off one item.',
    ],
  },
  {
    slug: 'library-reading-material',
    title: 'Make an item reading material, not homework',
    category: 'Sessions & notes',
    keywords: ['library', 'reading', 'reference', 'no log', 'nothing to fill in', 'guide', 'information', 'not homework'],
    summary: 'Turn off the logging question so an item is just something to read.',
    steps: [
      'Open the item in your Library.',
      'Find "Ask the client to log sessions".',
      'Leave it ON if you want them to record what they did and how it went — that counts towards their progress.',
      'Turn it OFF for reference material like "how to fit a harness". It appears in their app with nothing to fill in.',
      'Click "Save".',
    ],
  },
  {
    slug: 'reorder-library',
    title: 'Put your library in the order you want',
    category: 'Sessions & notes',
    keywords: ['library', 'order', 'reorder', 'drag', 'sort', 'move', 'rearrange', 'first'],
    summary: 'Drag categories, themes and items into the order that suits you.',
    steps: [
      'Click "Library" on the left. (You may have renamed it.)',
      'Drag a category by its handle to move it up or down.',
      'Open a category and drag its themes the same way.',
      'Open a theme and drag its items the same way.',
      'The order saves on its own, and it sets the tree, the drill-down on a phone, and every list that offers you a library item.',
    ],
  },
  {
    slug: 'rename-library-category',
    title: 'Rename or delete a category or theme',
    category: 'Sessions & notes',
    keywords: ['library', 'rename', 'delete', 'remove', 'edit', 'category', 'theme', 'settings', 'cog'],
    summary: 'Open the thing you want to change — its settings sit at the top.',
    steps: [
      'Click "Library" on the left, then open the category or theme.',
      'Click the cog button at the top, beside "New theme" (or "New item").',
      'Change the "Name" and click "Save".',
      'To remove it, click "Delete this category" (or theme) and confirm.',
      'Everything inside it goes too — but homework already handed out to clients is kept.',
    ],
  },
  {
    slug: 'duplicate-library-item',
    title: 'Copy or delete a library item',
    category: 'Sessions & notes',
    keywords: ['library', 'duplicate', 'copy', 'clone', 'delete', 'remove item', 'reuse'],
    summary: 'Make a copy to tweak, or take an item out of your library.',
    steps: [
      'Open the item in your Library.',
      'Click the "…" button at the top right.',
      'Click "Duplicate this item" to open a copy you can change.',
      'Or click "Delete this item", then confirm.',
      'Homework already handed out to clients is kept — only the library copy goes.',
    ],
  },

  // ── Homework ──────────────────────────────────────────────────────────────
  {
    slug: 'give-library-item-to-client',
    title: 'Give a library item to a client as homework',
    category: 'Sessions & notes',
    keywords: ['homework', 'assign', 'give', 'hand out', 'library', 'send exercise', 'set homework', 'task'],
    summary: 'Hand one exercise to one client, for a day you choose.',
    steps: [
      'Open the item in your Library.',
      'Click "Assign" at the top.',
      'Type in "Search clients or dogs…" and click the client you want.',
      'Pick a "Dog" if it is for one in particular.',
      'Set "When it\'s for" — the day it appears in their homework diary.',
      'Click "Add to their homework".',
    ],
  },
  {
    slug: 'add-homework-to-session',
    title: 'Add homework to a session',
    category: 'Sessions & notes',
    keywords: ['homework', 'session', 'after session', 'set tasks', 'library', 'custom task', 'add task'],
    summary: 'Attach exercises to the session you just ran.',
    steps: [
      'Click "Schedule" on the left and open the session.',
      'Open the "Homework" row.',
      'Click "Add from library", search for the exercise, and click it to add.',
      'Or click "Add custom task" to write a one-off in the box, with reps if you want.',
      'Each task lands in that client\'s homework straight away.',
    ],
  },
  {
    slug: 'default-homework-for-an-offering',
    title: 'Set the usual homework for a programme',
    category: 'Sessions & notes',
    keywords: ['homework', 'default', 'every session', 'curriculum', 'package', 'programme', 'course', 'set once', 'usual'],
    summary: 'Decide once what follows each session, then confirm it in one tap on the day.',
    steps: [
      'Click "1:1 Sessions" on the left and open the programme. (You may have renamed it.)',
      'Click the "Sessions" tab — it reads "Homework" if the programme is a single session.',
      'Click "Add homework" under the session number you want, and pick items from your Library.',
      'Use "Every session" for homework that follows every single one.',
      'On the day, the session screen shows "Usual homework for …" — tick what applies and press the "Add … tasks" button.',
    ],
  },
  {
    slug: 'who-has-library-item',
    title: 'See who already has a library item',
    category: 'Sessions & notes',
    keywords: ['library', 'who has', 'holders', 'assigned to', 'given to', 'register', 'clients'],
    summary: 'Every client who has been given this exercise, and when.',
    steps: [
      'Open the item in your Library.',
      'Click the "Who has this" tab at the top.',
      'Each row shows the client, their dog, when you last gave it, and how many they have marked done.',
      'Click a row to open that client.',
    ],
  },
  {
    slug: 'where-clients-see-homework',
    title: 'Where your client sees their homework',
    category: 'Sessions & notes',
    keywords: ['homework', 'client', 'what they see', 'this week', 'tick off', 'training log', 'client app', 'diary'],
    summary: 'Homework lands on their home screen for the day you set.',
    steps: [
      'Your client opens PupManager and lands on their home screen.',
      'Their homework is in the "This week" card, with a ring showing how much is done.',
      'They tap the circle beside a task to tick it off.',
      'They tap the task name to open it, read your instructions, and log how the training went.',
      'To see it yourself, open the client and click "View as client" under "Client actions".',
    ],
  },

  // ── Achievements ──────────────────────────────────────────────────────────
  {
    slug: 'choose-achievement-trigger',
    title: 'Choose when an achievement is earned',
    category: 'Sessions & notes',
    keywords: ['achievement', 'badge', 'trigger', 'rule', 'earned', 'automatic', 'streak', 'milestone', 'award'],
    summary: 'Pick the rule that hands a badge out on its own.',
    steps: [
      'Click "Achievements" on the left, under "Tools". (You may have renamed it.)',
      'Open an achievement, or click "Add achievement".',
      'Scroll to "How it\'s earned" and pick a "Trigger" — first session, sessions completed, homework streak, perfect weeks, and more.',
      'If the trigger asks for a number, type it in the box beside it.',
      'Pick "Manual — team awards" instead if you want to hand it out yourself.',
      'Turn "Published" on so clients can see it, then click "Save changes".',
    ],
  },
  {
    slug: 'award-achievement-by-hand',
    title: 'Give a client an achievement yourself',
    category: 'Sessions & notes',
    keywords: ['achievement', 'badge', 'award', 'manual', 'give', 'client', 'reward', 'by hand'],
    summary: 'Award a badge to one client without waiting for a rule.',
    steps: [
      'Click "Clients" on the left and open the client. (You may have renamed it.)',
      'Click the "Achievements" tab.',
      'Find the badge you want and click "Award".',
      'It shows on their achievements straight away.',
      'Click the button on an awarded row again if you need to take it back.',
    ],
  },

  // ── To do & Notes ─────────────────────────────────────────────────────────
  {
    slug: 'use-todo-screen',
    title: 'Use the To do screen',
    category: 'Sessions & notes',
    keywords: ['to do', 'todo', 'needs notes', 'to invoice', 'catch up', 'brain dump', 'list', 'jobs', 'outstanding'],
    summary: 'Everything still waiting on you — write-ups, invoices and your own list.',
    steps: [
      'On a phone, tap "To do" in the bar along the bottom.',
      'On a computer, click the "notes to write" or "to invoice" tile on your Dashboard.',
      'The "Notes" tab lists past sessions still needing a write-up or an invoice, oldest first.',
      'The "To do" tab is your own list — type in the box and press the plus to add one.',
      'The "Brain dump" tab is free notes that save as you type.',
    ],
  },
  {
    slug: 'notes-versus-to-do',
    title: 'Notes and To do — which is which',
    category: 'Sessions & notes',
    keywords: ['notes', 'to do', 'difference', 'confused', 'draft', 'unsent', 'needs notes', 'two lists'],
    summary: 'Two screens sound alike. One is work not started, the other is work not shown.',
    steps: [
      '"To do" lists past sessions where you have NOT written anything yet (or have not invoiced).',
      '"Notes" in the left menu lists write-ups you HAVE written on sessions you have not marked complete.',
      'So: To do = still to write. Notes = written, but the client cannot see it yet.',
      'Marking a session complete is what shows a write-up to the client.',
      'Open "Clients" in the left menu, then "Notes", to release one early with "Send".',
    ],
  },

  // ── Route ─────────────────────────────────────────────────────────────────
  {
    slug: 'turn-on-route-planner',
    title: 'Turn on the Route planner',
    category: 'Scheduling',
    keywords: ['route', 'route planner', 'driving', 'add-on', 'addon', 'turn on', 'locked', 'greyed out'],
    summary: 'Route is a paid add-on — switch it on before you can plan a day.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Add-ons" tab.',
      'Click the "Route planner" card, then "Learn more →".',
      'Click "Turn on Route planner".',
      '"Route" under "Tools" in the left menu stops being locked. It starts from your next billing cycle.',
    ],
  },
  {
    slug: 'set-route-base',
    title: 'Set the base your day starts from',
    category: 'Scheduling',
    keywords: ['route', 'base', 'home', 'start', 'yard', 'address', 'depot', 'starting point'],
    summary: 'Every route starts and ends at your base, so it has to be set first.',
    steps: [
      'Click "Route" on the left, under "Tools".',
      'Type your address into "Search your base address…".',
      'Pick your address from the suggestions. It saves as soon as you pick one.',
      'The day\'s route appears straight after.',
      'To change it later, click the pencil on the "Base · start & end" card.',
    ],
  },
  {
    slug: 'plan-day-route',
    title: 'Plan the order you drive your day in',
    category: 'Scheduling',
    keywords: ['route', 'driving order', 'optimise', 'optimize', 'shortest', 'map', 'stops', 'drive time', 'satnav', 'google maps'],
    summary: 'Pick a day, choose your stops, and get the driving order with times and distance.',
    steps: [
      'Click "Route" on the left, under "Tools".',
      'Tap the date at the top to change day, or use the arrows either side. (In "Schedule", clicking a day\'s date number opens its route.)',
      'Under "Stops", tap a row to take it off the route or put it back.',
      'Choose "Time order" to keep your booked times, or "Shortest drive" to let it reorder for the least driving.',
      'Click "Optimise route". You get a numbered run-sheet with drive times, plus the total time and distance.',
      'Click "Google Maps" on that run-sheet to open the whole route on your phone.',
    ],
  },
  {
    slug: 'route-skipped-stops',
    title: 'Fix stops the route planner left out',
    category: 'Scheduling',
    keywords: ['route', 'missing', 'not on the route', 'no address', 'no venue', 'online', 'virtual', 'skipped', 'left off'],
    summary: 'Anything it cannot drive to is listed with the reason and the fix.',
    steps: [
      'Click "Route" on the left and pick the day.',
      'Look at "Not on the route" below your stops.',
      '"No address on file" — click "Set address", search the client\'s address, and pick it. They join the route.',
      '"No venue set" — click "Add venue" to open that class or event and give it a location.',
      '"Online — nothing to drive to" is correct and needs nothing.',
    ],
  },

  // ── Google Calendar ───────────────────────────────────────────────────────
  {
    slug: 'connect-google-calendar',
    title: 'Connect your Google Calendar',
    category: 'Scheduling',
    keywords: ['google calendar', 'calendar', 'sync', 'sync my diary', 'connect', 'gcal', 'link calendar', 'ical'],
    summary: 'Link your own Google Calendar so your bookings show up in it.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Configure" tab and turn "Google Calendar" on. It costs nothing.',
      'Click "Connect a calendar" on that row — or go to the "Integrations" tab and click Manage on the "Google Calendar" card.',
      'Click "Connect Google Calendar" and sign in to Google.',
      'You come back to PupManager and it shows "Connected".',
      'This is YOUR calendar. Everyone on your team connects their own the same way.',
    ],
  },
  {
    slug: 'google-calendar-what-syncs',
    title: 'What goes to your Google Calendar, and what comes back',
    category: 'Scheduling',
    keywords: ['google calendar', 'sync', 'what syncs', 'busy', 'double booked', 'availability', 'two way', 'blocked out'],
    summary: 'Your bookings go out to Google; anything already in Google comes back as busy time.',
    steps: [
      'Your sessions, classes and blocked-out time appear in your own Google Calendar.',
      'Anything already in that calendar — a dentist appointment, say — shows on your PupManager schedule as busy.',
      'Busy time is a warning, not a block. You can still book over it if you mean to.',
      'It is per person, not per business: you see your own calendar, not your team\'s.',
      'Changes flow through on their own — there is nothing to press each time.',
    ],
  },
  {
    slug: 'google-calendar-backfill',
    title: 'Get older bookings into your Google Calendar',
    category: 'Scheduling',
    keywords: ['google calendar', 'missing', 'old sessions', 'classes not showing', 'backfill', 'sync now', 'catch up'],
    summary: 'Bookings made before you connected need one push.',
    steps: [
      'Open Settings, then the "Integrations" tab, then Manage on the "Google Calendar" card.',
      'Click "Sync my calendar now".',
      'It adds classes and sessions that were already booked before you connected.',
      'If it says some are still to go, press it again.',
      'Pressing it twice is safe — nothing is duplicated.',
    ],
  },
  {
    slug: 'disconnect-google-calendar',
    title: 'Stop syncing your Google Calendar',
    category: 'Scheduling',
    keywords: ['google calendar', 'disconnect', 'unlink', 'stop sync', 'remove', 'turn off calendar'],
    summary: 'Unlink your calendar when you no longer want things flowing into it.',
    steps: [
      'Open Settings, then the "Integrations" tab, then Manage on the "Google Calendar" card.',
      'Click "Disconnect" under the green "Connected" tag.',
      'Confirm. New sessions and changes stop syncing.',
      'Events already in your Google Calendar stay where they are.',
      'You can connect again any time with "Connect Google Calendar".',
    ],
  },

  // ── Tags (the basics are in "use-tags") ───────────────────────────────────
  {
    slug: 'manage-tags',
    title: 'Add, rename and reorder your tags',
    category: 'Programmes & products',
    keywords: ['tags', 'manage tags', 'rename tag', 'edit tag', 'reorder', 'order', 'labels', 'tidy up'],
    summary: 'Your one list of tags, with the order clients browse them in.',
    steps: [
      'Click "Tags" on the left, under Offerings. (You may have renamed it. It appears once you\'ve made your first tag — before that, use the "Tags" row on the Offerings screen.)',
      'Click "New tag", type a name like "Puppy", and click "Add".',
      'Click the pencil on a row to rename a tag, then press Enter.',
      'Drag a row by its handle to change the order.',
      'Renaming moves nothing — everything in the tag stays in it.',
    ],
  },
  {
    slug: 'delete-tag',
    title: 'Delete a tag — what happens to what\'s in it',
    category: 'Programmes & products',
    keywords: ['tags', 'delete tag', 'remove tag', 'get rid of', 'lose', 'safe', 'does it delete'],
    summary: 'Deleting a tag never deletes the things carrying it.',
    steps: [
      'Click "Tags" on the left, under Offerings. (You may have renamed it.)',
      'Click the bin icon on the tag\'s row.',
      'Read the message — it tells you how many things are in the tag.',
      'Click "Delete tag".',
      'The classes, sessions and products in it stay exactly as they are and stay on sale. Only the tag goes.',
    ],
  },
  {
    slug: 'open-a-tag',
    title: 'See the class and the product inside one tag',
    category: 'Programmes & products',
    keywords: ['tags', 'open tag', 'what is in a tag', 'contents', 'inside', 'shop', 'class', 'together'],
    summary: 'One screen showing everything under a word — offerings and shop items side by side.',
    steps: [
      'Click "Tags" on the left, under Offerings. (You may have renamed it.)',
      'Click a tag row to open it.',
      'It is split into headings — 1:1 Sessions, Group Classes, Casual Classes, Events, Doggy Daycare and "From the shop".',
      'Click any row to open that class, session or product.',
      'Click the X on a row to take that one thing out of the tag. The thing itself stays as it is.',
    ],
  },
  {
    slug: 'group-list-by-tag',
    title: 'Group an offerings list by tag',
    category: 'Programmes & products',
    keywords: ['tags', 'group by tag', 'sort by tag', 'headings', 'filter', 'find', 'long list'],
    summary: 'Break a long list into headings, one per tag.',
    steps: [
      'Open "1:1 Sessions", "Group Classes", "Casual Classes" or "Events" on the left. (You may have renamed them.)',
      'Click the tag icon in the bar above the list.',
      'The list splits into a run of cards under each tag name, with a count.',
      'Anything with no tag sits at the bottom under "No tag".',
      'Click the tag icon again to ungroup. Dragging to reorder comes back when you do — the saved order is one arrangement of the whole list.',
    ],
  },

  // ── Locations ─────────────────────────────────────────────────────────────
  {
    slug: 'add-location',
    title: 'Add the places you work from',
    category: 'Account & app',
    keywords: ['location', 'locations', 'venue', 'hall', 'park', 'field', 'address', 'where', 'place'],
    summary: 'Save a place once, with a photo and parking notes, then pick it later.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Locations" tab.',
      'Click "Add location".',
      'Type a "Name" — "The training field" — then search for the "Address".',
      'Add an "Image" and a "Description" if you like — parking, gate codes, where to meet.',
      'Click "Add location".',
    ],
  },
  {
    slug: 'use-saved-location',
    title: 'Use a saved place on a session or class',
    category: 'Account & app',
    keywords: ['location', 'venue', 'pick location', 'where it meets', 'choose location', 'class', 'session', 'address'],
    summary: 'Pick a saved place from the dropdown, or add a new one without leaving the page.',
    steps: [
      'Open the offering you\'re setting up and find "Location".',
      'Open the dropdown, which starts at "Choose location…", and pick a saved place.',
      'Not there yet? Click the "+" beside the dropdown to add one on the spot.',
      'On a programme with several sessions, each session in the list has its own "Location".',
      'A group class asks you to type its location instead — start typing and pick the address from the suggestions.',
    ],
  },

  // ── Making the app yours ──────────────────────────────────────────────────
  {
    slug: 'rename-menu-items',
    title: 'Call the menu what you call it',
    category: 'Account & app',
    keywords: ['rename', 'menu', 'wording', 'labels', 'what you call things', 'services', 'offerings', 'language', 'naming'],
    summary: 'Change our words in your left menu to the words your business uses.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "What you call things" tab.',
      'Find the row with our word on the left — "Offerings", say.',
      'Type your word in the box beside it: "Services", "Training", whatever you say.',
      'Click "Save names". The left menu changes straight away.',
      'Leave a box blank to go back to our word, or click the undo arrow on that row. Only an owner or manager can change these.',
    ],
  },
  {
    slug: 'configure-free-features',
    title: 'Turn included features on and off',
    category: 'Account & app',
    keywords: ['configure', 'switch on', 'switch off', 'features', 'included', 'free', 'hide', 'declutter', 'simplify', 'missing menu'],
    summary: 'The switchboard for everything that comes with your plan. Nothing here costs extra.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Configure" tab.',
      'The features are grouped: "What you offer", "Taking money", "Running the business", "Connected to other apps".',
      'Tap a switch to turn something on or off. Its menu row appears or disappears.',
      'When something is on and needs setting up, a link appears under it — "Connect a calendar", "Open the library".',
      'Paid extras are not here. They live on the "Add-ons" tab.',
    ],
  },
  {
    slug: 'home-screen-photo',
    title: 'Put a photo on your home screen',
    category: 'Account & app',
    keywords: ['home screen', 'photo', 'background', 'image', 'banner', 'hero', 'design', 'branding', 'greeting', 'logo'],
    summary: 'A photo behind the top of your home screen, fading out over the rows below.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Design" tab and open "Home screen image".',
      'Click "Upload image" under "Background photo" and pick a photo. A wide, calm one works best.',
      'Watch the phone preview beside it — that is the real home screen.',
      'Untick "Show my logo and greeting" if you want just the photo.',
      'It saves as you go. This is your business\'s home screen — everyone on your team sees the same one.',
    ],
  },
  {
    slug: 'check-integrations',
    title: 'See what PupManager is connected to',
    category: 'Account & app',
    keywords: ['integrations', 'connected', 'connections', 'stripe', 'xero', 'google calendar', 'website', 'status', 'not working'],
    summary: 'One screen for every outside service, and whether it is actually working.',
    steps: [
      'Open Settings (the cog at the top right, or the menu on a phone).',
      'Click the "Integrations" tab.',
      'Each card says what it does and where it stands: "Connected", "Finish connecting" or "Not set up".',
      '"Finish connecting" means it is switched on but nothing is linked yet — that is the one to deal with.',
      'Click Manage on a card to open its own settings.',
    ],
  },
  {
    slug: 'phone-app-layout',
    title: 'Find your way around on a phone',
    category: 'Account & app',
    keywords: ['phone', 'mobile', 'app', 'bottom bar', 'tabs', 'menu', 'where is', 'cant find', 'ios', 'android', 'navigation'],
    summary: 'What the five tabs are, and where the rest of the app hides.',
    steps: [
      'The bar along the bottom has five tabs: Home, Schedule, To do, Messages and Alerts.',
      'Everything else is behind the menu button at the top left.',
      'The "+" at the top right creates things — a client, a session, a sale.',
      'The magnifying glass beside it searches everything.',
      'On a detail screen the menu button becomes a back arrow.',
      'Billing is not shown inside the app — open PupManager in a web browser to change your plan.',
    ],
  },
]
